unbind C-b
unbind '"'
unbind %

set-option -g prefix C-a
bind-key C-a send-prefix

bind v split-window -h -c '#{pane_current_path}'
bind b split-window -c '#{pane_current_path}'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.tmux.conf \; display-message "Reloaded .tmux.conf"

set-window-option -g mode-keys vi

########### Shell theme config ##################
run-shell ~/.tmux/plugins/tmux-nova/nova.tmux
